development:
  adapter: postgres
  server: localhost
  database: jobspotting
  pool: 5
  timeout: 5000
  username: curiost
  password: curiost

production:
  adapter: postgres
  server: -heroku-
  encoding: utf8
  reconnect: false
  database: -heroku-
  pool: 5
  username: -heroku-
  password: -heroku-
